### ISSUE TITLE
Poor WPF performance

### ISSUE THREAD

**Issue by BHandle** [beto-rodriguez/LiveCharts2#1237]
In recent versions (I'm unsure when it started), WPF performance has degraded severely anytime charts need updating, even below V0 performance.   Thinking I had somehow broken something or had tuned update settings badly, I switched to running the samples and am able to replicate this with the LV2 samples.  Winforms performs as expected.

When run under WPF on my system:
* */AutoUpdate has very high usage (12% cpu utilization), despite only updating once a second.   (Winforms: 1-2%)
* General/Scrollable utilizes 16%, and only updates once a second or so when dragging.   (Winforms:0-10% usage, buttery smooth)
* General/MultiThreading updates infrequently and causes the UI to become unresponsive  (I have to force close and reopen)  (Winforms 8%, smooth)
* General/Realtime 14%, but still responsive  (WinForms: 6-10%)

Running this in VS, I can see that a lot of time is being spent in doing layout operations in Skia:
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/3092680/e13204fa-96f2-4e19-ba73-605eed08dfe0)

This is on Windows 10, i7 quad core.  Let me know if there is any other information that would be helpful!

**Comment by tripleacoder** [comment]
I also have poor performance in my WPF Cartesian chart. I have 1 series with 60k points (ObservablePoint).


```
private List<ISeries> chartDataSeries = new List<ISeries>();

public List<ISeries> ChartDataSeries
{
    get
    {
        return this.chartDataSeries;
    }
}

private void AddPlotSeriesToLiveChart(PlotVM plotVM)
{
    var series = new LineSeries<ObservablePoint>
    {
        Stroke = new SolidColorPaint(SKColors.Blue) { StrokeThickness = 1 },
        LineSmoothness = 0,
        GeometrySize = 0,
        Fill = null,
    };

    var values = new List<ObservablePoint>();
    foreach (DataRow dataRow in plotVM.Result.Rows)
    {
        double x = (Convert.ToDateTime(dataRow["DateTime"]) - plotVM.Process.StartTime).TotalHours;
        double y = Convert.ToDouble(dataRow["Value"]);
        values.Add(new ObservablePoint(x, y));
    }
    series.Values = values;
    this.chartDataSeries.Add(series);
    this.NotifyPropertyChanged(nameof(this.ChartDataSeries));
}
```

I don't do any updates to the data, but when I resize the chart or move the mouse around it, it is very laggy.

**Comment by beto-rodriguez** [comment]
@tripleacoder The current version of the library is designed for ~10k points, you must virtualize the points in your chart to get a better performance, I think that your issue is different than the one reported in this issue.

@BHandle its strange, I get a good performance, also it seems that @tripleacoder is getting a better performance than you, how many points are in your chart @BHandle?

**Comment by BHandle** [comment]
Since I'm able to replicate it with the samples, I've just fallen back to them for this report to remove any user error.

General/Scrollable uses 500 points, and while it is able to stay responsive, scrolling only updates (visually) once every ~1-2s or so.

It doesn't feel like it's the number of points doing it, but rather that there is an expensive call being made into Skia everytime the graph has to update.  I can trigger this by adding points or scrolling.  I ran this under a few profilers, and I'll try a few more today, but most point to it being a layout size calculation, but I have yet to get a full call stack.

**Comment by beto-rodriguez** [comment]
To discard an SkiaSharp issue, you could roll back to an older version of SkiaSharp, I have been constantly updating it.

**Comment by BHandle** [comment]
If anything, 2.88.0 is even worse.  Just waving the mouse over the chart is enough to take it to 15% on the Scrollable sample.  To help show what I'm seeing, I took a quick video comparing the same sample in WinForms  (left) and WPF (right)

https://github.com/beto-rodriguez/LiveCharts2/assets/3092680/25f93b78-3516-4f36-99d7-440f9c42a9fe

With the same number of points, the exhibited behavior is quite different.  WinForms remains smooth and while there is a CPU spike when dragging, it's nowhere near enough to saturate the main thread.  In WPF, just trying to show the tooltips is enough to saturate, and some of the scrolls take up to two seconds to actually act.

**Comment by BHandle** [comment]
When I attach a profiler, I can see that it spends 97% of the time in kernel time, of which 10% is redrawing skia:
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/3092680/f16dc466-7ce3-4753-a220-369899337cff)

No idea what the rest of the time is spent on, perhaps just the profiler itself.
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/3092680/4f93547f-ed6c-46e4-8ef4-fb595a53dd33)

**Comment by beto-rodriguez** [comment]
strange, I need to find a way to replicate this, I get a decent performance:

![memeory](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/728ee6cb-c9c9-475d-a035-6d518808cfcb)

In WPF, I have seen some issues getting fixed by updating your GPU driver, can you try that?

**Comment by BHandle** [comment]
Well, that's believable as the computer I had been running on was a laptop with a NVidia Quadro, which sometimes have... strange behavior.  I updated the driver on it but am still seeing the same behavior following the update.

However, following your question I also copied the samples over to my personal desktop  (which, while an older processor, does have a discrete GPU), and I see smooth movement and CPU utilization ~6% for both WinForms and WPF.  Which was interesting, and further prompted me to add the GPU utilization to the task manager.  On my desktop, WPF is seeing ~20% gpu utilization... and the laptop is seeing 0%.  I suspect it's not even seeing the GPU and just using the integrated graphics of the Intel i7.  It's doing everything on the CPU and bogging down the main thread.

The target client for our use case is in an industrial setting and GPUs are sometimes used to drive 5+ monitors, and sometimes skipped entirely.  Other than perhaps providing a GPU acceleration toggle where I use either a V0 WPF chart or a WPF-hosted WinForms implementation, do you have any advice on how to proceed?   I'm not the most familiar with skiaSharp or any custom configuration I can do on my end, but if I can't rely on it to do the right thing on the target computer, I'm thinking implementing my own fallback may be the safest alternative.

**Comment by beto-rodriguez** [comment]
@tripleacoder see #486

**Comment by beto-rodriguez** [comment]
@BHandle it is strange, I keep trying to reproduce, in my case, I turned off the GPU (integrated) and even without it, everything seems to run smoothly.

![gpu](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/e38b75cc-9232-49b4-b728-f674d765c052)

**Comment by BHandle** [comment]
Well, it may be a false lead, but skia is definitely utilizing the GPU when it is available.  I added GPU to the windows task manager and I can see it using it on my desktop  (only when I drag around.  Utilization is 0% when idle): 

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/3092680/e41496a5-9a49-4dd5-81ce-9b5e7fa138e2)

but the work laptop (where things slow down) is not:

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/3092680/dbd2ba37-fabe-4fec-81e5-97517a978bc7)

Again, that _could_ be unimportant, but it's the best lead I've currently got, as the WPF is smooth on my desktop.  I've tried to force using the GPU in both the Windows settings and the Nvidia control panel, but it still doesn't use it.  That probably means skia is using a particular feature to key into using the GPU or not, and the Quadro doesn't have it, so it isn't even trying.   


Is there anything you want me to try that might help?

**Comment by beto-rodriguez** [comment]
@mattleibow can you give us a hint?

**Comment by beto-rodriguez** [comment]
I am not completely sure if this was part of the issue, but in the latest version of the library we can enable GPU rendering by calling `LiveCharts.UseGPU = true;` when the app starts.

I will close this for now, but feel free to reply or create a new issue if this does now fix the issue.

**Comment by c0nstexpr** [comment]
> I am not completely sure if this was part of the issue, but in the latest version of the library we can enable GPU rendering by calling `LiveCharts.UseGPU = true;` when the app starts.
> 
> I will close this for now, but feel free to reply or create a new issue if this does now fix the issue.

I try the new version with `LiveCharts.UseGPU = true;`, but doesn't get any improvement. (Ryzen 5800 and RTX 3060)
The performance bottleneck seems like to be other place.

**Comment by beto-rodriguez** [comment]
@c0nstexpr how many points?

**Comment by c0nstexpr** [comment]
> [@c0nstexpr](https://github.com/c0nstexpr) how many points?

10000 is fine, but not more 50000

**Comment by pm-kuerten** [comment]
In my project I essentialy recreated the [Scrollable Charts](https://livecharts.dev/docs/WPF/2.0.0-rc5.4/samples.general.scrollable#scrollable-charts) sample with roughly 15k points. I also have set `LiveCharts.UseGPU = true`.
Both Charts run with 30 FPS but moving either of them has a roughly 0.5s delay before the chart reacts.

But if I limit the number of points to 100 it is as smooth as in the example.
