### ISSUE TITLE
scrolling on a pie chart causes program to crash.

### ISSUE THREAD

**Issue by FardinFarnezhad** [beto-rodriguez/LiveCharts2#1265]
Hello I hope you are having a great day. 
on the pre release version when i scroll on the pie chart it causes the program to crash.
i am on .net maui Windows platform and the pie chart is on a scrollview if my cursor is inside of the pie chart the program crashes.
since pie charts does not have a zoom mode property i don't know what to do to. let me know if there is a workaround for this problem.
EDIT: it does not matter where the pie chart is if the mouse cursor is on the chart any scroll will cause the program to crash.

**Comment by FardinFarnezhad** [comment]
Update : i downgraded to beta 950 and this bug does not exist. since this is a critical bug for my program i cannot use the latest update. i don't think a code sample is necessary but let me know if you need anything.

**Comment by beto-rodriguez** [comment]
Thanks for the report, and sorry about that, this is fixed in rc.1.1

**Comment by FardinFarnezhad** [comment]
unfortunately the problem still persists for me even after the rc 1.1 update maybe i am doing something wrong?

**Comment by beto-rodriguez** [comment]
Completely my bad.... new version published again rc1,2
