### ISSUE TITLE
Long X-axis labels overlap, making them unreadable (e.g. dates)

### ISSUE THREAD

**Issue by EricEzaM** [beto-rodriguez/LiveCharts2#471]
**Describe the bug**
X-axis labels overlap when they are long and are thus unreadable. For example, using dates. 
Related: #424

Non-ideal workaround: Use the label rotation e.g. -20.

**To Reproduce**
Follow the default implementation in [the docs](https://lvcharts.com/docs/WPF/2.0.0-beta.220/Overview.Installation), and then bind the axes:

```cs
public Axis[] XAxes { get; set; } = new[]
        {
            new Axis()
            {
                Labeler = point => $"Long label: {point}"
            },
        };
```

**Expected behavior**
Ideally, the labels which cause overlaps would not be rendered. So in the case below, labels 0, 2, 4 and 6 would be kept, and the other not rendered (assuming 0,2,4,6 do not overlap eachother). I guess you would always want _some_ labels, so the first and last point could be forced on even if they overlap - then it is up to the user to fix their label formatter.

**Screenshots**
![image](https://user-images.githubusercontent.com/41730826/168191161-60e70121-53cb-4a2d-b74f-f767af0cf115.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, .NET Framework 4.8

**Comment by korneliuscode** [comment]
I'm experiencing the same. Thanks for reporting.

**Comment by beto-rodriguez** [comment]
This is fixed with the referenced PR and will be included in the next version of the library, thanks for the report!

**Comment by EricEzaM** [comment]
Hi @beto-rodriguez, there are some edge cases where this appears to still not be fixed. To reproduce:

Modify `samples/ViewModelsSamples/Axes/DateTimeScaled/ViewModel.cs` to be:

```cs
public partial class ViewModel : ObservableObject
{
    static IEnumerable<DateTimePoint> GenValues(int count)
    {
        var arr = new DateTimePoint[count];

        arr[0] = new DateTimePoint(DateTime.Now, 0);
        for (int i = 1; i < count; i++)
        {
            arr[i] = new DateTimePoint(arr[i - 1].DateTime.AddSeconds(i), i);
        }

        return arr;
    }

    public ISeries[] Series { get; set; } =
    {
        new LineSeries<DateTimePoint>
        {
            Values = new ObservableCollection<DateTimePoint>(GenValues(100)),
            LineSmoothness = 0,
        }
    };

    public Axis[] XAxes { get; set; } =
    {
        new DateTimeAxis(TimeSpan.FromSeconds(1), date => date.ToString("d/M/yy HH:mm:ss"))
    };
}
```

Add `ZoomMode="X"` to the view (I am using WPF)

Run the app, go to Axes/DateTimeScaled and observe:

https://github.com/beto-rodriguez/LiveCharts2/assets/41730826/24408dad-6851-47cd-9594-f5b88ae5500c

**Comment by korneliuscode** [comment]
I actually also still have this behavior on some charts with date values (in different formats).

**Comment by beto-rodriguez** [comment]
I made improvements to the labels measurement, in the next version (rc2) the library is much better at it, at least I can no longer reproduce with your snippet @EricEzaM:

![scroll](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/4eec7a27-7ce8-4ce3-bfc3-ab696b962c0a)
